### ISSUE TITLE
What are the rules for setting the parameters of vit-tiny's decoder？

### ISSUE THREAD

**Issue by zzzzzzyang** [IcarusWizard/MAE#10]
Thanks for your work! I’m pretraining the vit-tiny for my dataset, about 260k images. But i can not determine the setting for decoder's parameters (depth/embed_dim/num_heads),  just consistent with vit-base/large/huge or choose some smaller value to make a lightweight decoder? Due to the limitation of gpus, i can not try many times. Could you give me some suggestions, thanks a lot. :)

**Comment by IcarusWizard** [comment]
Thanks for your question. But I may not be the correct person to answer this question, since due to the limitation of computation resources, I did not tune these parameters either.

From the Sec.4.1 of the MAE paper, the depth of the decoder does not have a much influence on the performance, while the width mostly influences the linear-probe result but not much on the fine-tuning ones. So I would suggest to use `depth=1, embed_dim=512,num_heads=16`, the parameter in the original implementation with `depth=1`. And see if it works, if not, gradually increase the `depth`.

Hope this helps.
