### ISSUE TITLE
extracting embeddings

### ISSUE THREAD

**Issue by donovanr** [IcarusWizard/MAE#8]
Hi, how would you recommend extracting (1D) image embeddings from the model on (say) a held out data set?

**Comment by IcarusWizard** [comment]
Hi, if I understand your question correctly, you want to use a 1D representation learned by MAE to your downstream tasks. Then the answer depends on how you would like to use the model.

Generally, for an image, the MAE encoder will output a tensor in shape [T+1, F], where the T is the number of tokens you split the image (i.e. h * w / p^2), and the plus 1 here is for the `cls_token`; and F is the feature size. There are two ways to conclude a 1D representation from the Encoder:
1. Use the first feature, which is feature from `cls_token`.
2. Average the features except for the first `cls_token` related feature.

If you will do some fine-tuning in your downstream task. I think either way is okay. However, if you won't do some fine-tuning, I think only the second way is valid, since there is no force of using the `cls_token` in the course of MAE training.
